version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8077:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: your_db_password
    volumes:
      - ./wordpress_data:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: your_db_password
    volumes:
      - ./db_data:/var/lib/mysql

  # nginx:
  #   image: nginx:stable-alpine
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "80:80"
  #     - "443:443" # For SSL if used
  #   volumes:
  #     - ./nginx-conf:/etc/nginx/conf.d
  #     - ./wordpress_data:/var/www/html # To serve static assets
  #   restart: always

volumes:
  wordpress:
  db: